/********************************************************************
* source/L1Classes.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error source/L1Classes.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableL1Classes();
extern void G__cpp_setup_inheritanceL1Classes();
extern void G__cpp_setup_typetableL1Classes();
extern void G__cpp_setup_memvarL1Classes();
extern void G__cpp_setup_globalL1Classes();
extern void G__cpp_setup_memfuncL1Classes();
extern void G__cpp_setup_funcL1Classes();
extern void G__set_cpp_environmentL1Classes();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/L1Classes.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__L1ClassesLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlEunsignedsPlongsPlongcOallocatorlEunsignedsPlongsPlonggRsPgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__L1ClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__L1ClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__L1ClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__L1ClassesLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__L1ClassesLN_L1Analysis;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisCSCTFDataFormat;
extern G__linked_taginfo G__L1ClassesLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__L1ClassesLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisCaloTPDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisDTTFDataFormat;
extern G__linked_taginfo G__L1ClassesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisEventDataFormat;
extern G__linked_taginfo G__L1ClassesLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__L1ClassesLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisGCTDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisGMTDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisGTDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisGeneratorDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisL1ExtraDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisL1MenuDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisRCTDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisRecoClusterDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisRecoJetDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisRecoMetDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisRecoMuonDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisRecoTrackDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisRecoVertexDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisSimulationDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisL1ExtraUpgradeDataFormat;
extern G__linked_taginfo G__L1ClassesLN_L1AnalysiscLcLL1AnalysisPhaseIIDataFormat;

/* STUB derived class for protected member access */
